### ISSUE TITLE
Update the project dependencies

### ISSUE THREAD

**Issue by yshyn-iohk** [hyperledger/identus-docs#110]
There are a lot of dependencies that `can` be updated.
`yarn outdate` command returns the following information:
<img width="1308" alt="image" src="https://github.com/hyperledger/identus-docs/assets/102033808/99965ec1-657a-4ab5-a7ec-5e8cbfceb8c5">

**Comment by FabioPinheiro** [comment]
`yarn outdated`

**Comment by FabioPinheiro** [comment]
This is Done
