### ISSUE TITLE
Reconsider the usage of log4brains ADRs site generator as it's outdated and is not properly maintained by the owner

### ISSUE THREAD

**Issue by yshyn-iohk** [hyperledger/identus-docs#131]
[log4brain](https://github.com/thomvaill/log4brains) is used to generate a [website with ADRs](https://staging-docs.atalaprism.io/adrs/)

The problems with this tool:
- it's outdated, contains a lot of vulnerability, and runs on node 16
- it has another style (compared to the current Docusaurus style that is configured)

Considered options:
- have a static pages with all ADRs as a part of the documentation portal
- consider another tool instead of the log4brains (research is required)

Output log example:
`npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

npm WARN deprecated @material-ui/styles@4.11.5: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.

npm WARN deprecated @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.

npm WARN deprecated @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September [20](https://github.com/hyperledger/identus-docs/actions/runs/9852910344/job/27202354787#step:6:21)21. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.`

**Comment by FabioPinheiro** [comment]
We no longer we log4brains
