### ISSUE TITLE
ARDs are not available in the latest version of the docs deployed to the GitHub pages

### ISSUE THREAD

**Issue by yshyn-iohk** [hyperledger/identus-docs#143]
As described in the subject, the ADRs are missing for some reason.

Blocken link: https://hyperledger.github.io/identus-docs/adrs

Screenshot:
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/4f77ee44-6d46-4801-8ecb-676c717af030">

**Comment by yshyn-iohk** [comment]
Assigned to @FabioPinheiro to figure out what is wrong.

@FabioPinheiro, if the ADRs engine doesn't work correctly with the GitHub pages, let's consider moving the ADRs from the cloud agent project to the docs as static files.

**Comment by FabioPinheiro** [comment]
![Screenshot 2024-08-12 at 13 59 58](https://github.com/user-attachments/assets/b4e7862b-7884-4ad4-a5f6-b21e2c9a74ef)

**Comment by FabioPinheiro** [comment]
This is how it looks now

cc @yshyn-iohk @elribonazo

**Comment by FabioPinheiro** [comment]
This is Done
